CREATE DATABASE IF NOT exists Grocery;
use Grocery;
-- 1. Suuplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY AUTO_INCREMENT,
    sup_nm VARCHAR(255),
    addr TEXT
);
-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY AUTO_INCREMENT,
    cat_nm VARCHAR(255)
);

-- 3. Emp Table
CREATE TABLE IF NOT EXISTS emp (
    emp_id TINYINT PRIMARY KEY AUTO_INCREMENT,
    emp_nm VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customer table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    cust_nm VARCHAR(255),
    addr TEXT
);

-- 5. Product Table
CREATE TABLE IF NOT EXISTS products (
    pro_id TINYINT PRIMARY KEY AUTO_INCREMENT,
    pro_nm VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10 , 2 ),
    FOREIGN KEY (sup_id)
        REFERENCES supplier (sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id)
        REFERENCES categories (cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);


-- 6. Orders table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id)
        REFERENCES customers (cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id)
        REFERENCES emp (emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    pro_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10 , 2 ),
    total_price DECIMAL(10 , 2 ),
    FOREIGN KEY (ord_id)
        REFERENCES orders (ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (pro_id)
        REFERENCES products (pro_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);



SELECT * FROM supplier;
SELECT * FROM categories;
SELECT * FROM emp;
SELECT * FROM customers;
SELECT * FROM products;
SELECT * FROM orders;
SELECT * FROM order_details;


-- Findinding insights 
-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.
-- How many unique customers have placed orders?

SELECT 
    COUNT(DISTINCT (cust_nm)) as unique_customers
FROM
    customers;  
    
    # 122 Unique customers it means 78 customers are repeating

-- Which customers have placed the highest number of orders?

SELECT 
    c.cust_id, c.cust_nm, COUNT(o.ord_id) AS total_orders
FROM
    customers c
        JOIN
    orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id , c.cust_nm
ORDER BY total_orders DESC
LIMIT 1;   # Jyotika ord 7


-- What is the total and average purchase value per customer?
SELECT 
    c.cust_id, c.cust_nm, COUNT(o.ord_id) AS total_orders
FROM
    customers c
        JOIN
    orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id , c.cust_nm
ORDER BY total_orders DESC
LIMIT 1;

-- Who are the top 5 customers by total purchase amount?
SELECT 
    c.cust_nm, SUM(od.total_price) AS total_purchase
FROM
    order_details od
        JOIN
    customers c ON c.cust_id = od.ord_id
GROUP BY c.cust_nm
ORDER BY total_purchase DESC
LIMIT 5;

-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.
-- How many products exist in each category?

SELECT 
    c.cat_nm, COUNT(p.cat_id) AS exist_pro
FROM
    categories c
        JOIN
    products p ON c.cat_id = p.cat_id
GROUP BY c.cat_nm;



-- What is the average price of products by category?

SELECT 
    c.cat_nm, AVG(p.price) AS avg_price
FROM
    categories c
        JOIN
    products p ON c.cat_id = p.cat_id
GROUP BY c.cat_nm;


-- Which products have the highest total sales volume (by quantity)?
SELECT 
    p.pro_id, p.pro_nm, SUM(od.quantity) AS highest_Sal
FROM
    products p
        JOIN
    order_details od ON p.pro_id = od.pro_id
GROUP BY od.pro_id
ORDER BY highest_Sal DESC;

-- What is the total revenue generated by each product?
SELECT 
	p.pro_id, p.pro_nm, SUM(od.total_price) AS total_revenue
FROM 
	products p
JOIN
	order_details od 
ON 
	p.pro_id = od.pro_id
GROUP BY
	p.pro_id, p.pro_nm
ORDER BY 
	total_revenue DESC limit 5;

-- How do product sales vary by category and supplier?
SELECT 
    c.cat_nm AS Categories,
    s.sup_nm AS Supplier_Name,
    SUM(od.quantity) AS Total_Qty_Sold,
    SUM(od.total_price) AS total_revenue
FROM
    order_details od
        JOIN
    products p ON od.pro_id = p.pro_id
        JOIN
    categories c ON p.cat_id = c.cat_id
        JOIN
    supplier s ON p.sup_id = s.sup_id
GROUP BY c.cat_nm , s.sup_nm
ORDER BY total_qty_sold DESC;



-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- ●​How many orders have been placed in total?​
SELECT 
    COUNT(ord_id) AS Total_Orders
FROM
    orders;


-- ●​What is the average value per order?​
-- -------------

SELECT 
    AVG(order_total) AS average_value_per_order
FROM
    (SELECT 
        ord_id, SUM(quantity * each_price) AS order_total
    FROM
        order_details
    GROUP BY ord_id) AS order_totals;

-- ●​On which dates were the most orders placed?​

SELECT 
    o.order_date, COUNT(od.quantity) AS total_ord
FROM
    orders o
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY o.order_date
ORDER BY total_ord DESC
LIMIT 1;



-- ●​What are the monthly trends in order volume and revenue?​
use grocery;
SELECT 
    YEAR(STR_TO_DATE(o.order_date, '%m/%d/%Y')) AS order_month,
    MONTHNAME(STR_TO_DATE(order_date, '%m/%d/%Y')) AS month_name,
    COUNT(od.quantity) AS total_ord,
    SUM(od.quantity * each_price) AS total_revenue
FROM
    orders o
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY order_month , month_name
ORDER BY total_ord DESC limit 5;


-- ●​How do order patterns vary across weekdays and weekends?

SELECT 
    YEAR(STR_TO_DATE(o.order_date, '%m/%d/%Y')) AS order_month,
    DAYNAME(STR_TO_DATE(order_date, '%m/%d/%Y')) AS Day_name,
    COUNT(od.quantity) AS total_ord,
    SUM(od.quantity * each_price) AS total_revenue
FROM
    orders o
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY order_month , Day_name
ORDER BY total_ord DESC;




-- 4. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- ●​How many suppliers are there in the database?​

SELECT DISTINCT
    (COUNT(sup_nm)) countOf_supplier
FROM
    supplier;

-- ●​Which supplier provides the most products?​

SELECT 
    sup_nm, COUNT(p.pro_id) AS pro_count
FROM
    products p
        JOIN
    supplier s ON p.sup_id = s.sup_id
GROUP BY sup_nm
ORDER BY pro_count DESC
LIMIT 1;


-- ●​ What is the average price of products from each supplier?​

SELECT 
    sup_nm,              
    avg(p.price) AS avg_price  
FROM 
    products p
JOIN 
    supplier s ON p.sup_id = s.sup_id
GROUP BY 
    sup_nm
ORDER BY 
    avg_price DESC;


-- ● ​Which suppliers contribute the most to total product sales (by revenue)?

SELECT 
    sup_nm, SUM(od.quantity * each_price) AS total_revenue
FROM
    products p
        JOIN
    supplier s ON p.sup_id = s.sup_id
        JOIN
    order_details od ON p.pro_id = od.pro_id
GROUP BY sup_nm
ORDER BY total_revenue DESC
LIMIT 5;


-- 5. Employee Performance
-- Access how employees are handling and influencing sales.
-- ● ​How many employees have processed orders?​

SELECT 
    COUNT(DISTINCT emp_id)
FROM
    orders;

-- ●​Which employees have handled the most orders?​

SELECT 
    emp_id, COUNT(emp_id) AS handle_ord
FROM
    orders
GROUP BY emp_id
ORDER BY handle_ord DESC
LIMIT 5;


-- ●​What is the total sales value processed by each employee?​

SELECT 
    o.emp_id, SUM(od.quantity * od.each_price) AS total_sales
FROM
    orders o
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY emp_id
ORDER BY emp_id;



-- ●​What is the average order value handled per employee?

SELECT 
    emp_id, AVG(order_total) AS avg_order_value
FROM
    (SELECT 
        o.emp_id,
            o.ord_id,
            SUM(od.quantity * od.each_price) AS order_total
    FROM
        orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.emp_id , o.ord_id) AS emp_orders
GROUP BY emp_id
ORDER BY avg_order_value DESC;


-- 6. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.

-- ● ​What is the relationship between quantity ordered and total price?​

SELECT 
    quantity, AVG(total_price) AS avg_price
FROM
    order_details
GROUP BY quantity
ORDER BY quantity;
    
-- Positive relationship


-- ●​ What is the average quantity ordered per product?​
SELECT 
    p.pro_id, p.pro_nm, AVG(od.quantity) AS avg_qty
FROM
    order_details od
        JOIN
    products p ON od.pro_id = p.pro_id
GROUP BY p.pro_id , p.pro_nm;


-- ●​How does the unit price vary across products and orders?
SELECT 
    p.pro_id,
    p.pro_nm,
    MIN(od.each_price) AS min_price,
    MAX(od.each_price) AS max_price,
    (MAX(od.each_price) - MIN(od.each_price)) AS price_difference,
    AVG(od.each_price) AS avg_price
FROM
    order_details od
        JOIN
    products p ON od.pro_id = p.pro_id
GROUP BY p.pro_id , p.pro_nm
ORDER BY price_difference DESC;



